[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "ptbuilder"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "h5py",
    "matplotlib",
    "cosmoTransitions",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ptbuilder*"]
